import type { Section } from '../types';

export const section3_6: Section = {
  id: '3.6',
  title: 'Integration and the Unity of Experience [INTERPRETED]',
  epistemicStatus: 'interpreted',
  content: [
    {
      type: 'note',
      variant: 'editorial',
      content:
        '**Epistemic status: INTERPRETED.** This section interprets the unity of consciousness and the binding problem through distinction-vocabulary. The global workspace theory is IMPORTED from neuroscience (Baars). Our contribution is reframing this in terms of thermodynamic optimization of distinction-maintenance—this is interpretation, not derivation.',
    },
    {
      type: 'paragraph',
      content:
        'One of the most striking features of consciousness is its unity. Despite being generated by billions of neurons across distributed brain regions, conscious experience presents as a single, unified field. The "binding problem" asks how this unity emerges from distributed processing.',
    },
    {
      type: 'heading',
      level: 2,
      content: 'Integration as Thermodynamic Optimization',
      id: 'integration-thermodynamic-optimization',
    },
    {
      type: 'paragraph',
      content:
        'Our framework suggests that unity emerges from thermodynamic constraints on distinction-maintenance:',
    },
    {
      type: 'list',
      style: 'numbered',
      items: [
        {
          content:
            '**Isolated boundaries are expensive**: Maintaining many unrelated distinction-states costs more than maintaining an integrated network where distinctions share resources.',
        },
        {
          content:
            '**Integration enables prediction**: A unified model of self-and-world is more useful for prediction and action than fragmented, disconnected models.',
        },
        {
          content:
            '**Coherence reduces conflict**: Contradictory distinctions require resolution, which costs energy. Integration eliminates contradictions, reducing overhead.',
        },
        {
          content:
            '**Global access enables flexible response**: A unified workspace allows any distinction to be combined with any other for novel responses—computationally powerful despite the energy cost.',
        },
      ],
    },
    {
      type: 'paragraph',
      content:
        'The brain has evolved to integrate distinctions into a unified field because fragmentation would be even more expensive and less functional.',
      emphasis: 'key',
    },
    {
      type: 'heading',
      level: 2,
      content: 'The Global Workspace Architecture',
      id: 'global-workspace-architecture',
    },
    {
      type: 'paragraph',
      content:
        'Neurally, integration is implemented through what Bernard Baars called the "global workspace"—a network of long-range connections (primarily thalamocortical and corticocortical) that allows information to be broadcast across brain regions.',
    },
    {
      type: 'paragraph',
      content: 'In boundary terms:',
    },
    {
      type: 'list',
      style: 'bullet',
      items: [
        {
          content:
            'Local distinction-making occurs in specialized modules (V1 for visual features, A1 for auditory features, etc.)',
        },
        {
          content:
            'Integration occurs when these local distinctions gain access to the global workspace',
        },
        {
          content:
            'Conscious experience corresponds to what is currently integrated in the workspace',
        },
        {
          content:
            'Unconscious processing corresponds to local distinctions that have not gained global access',
        },
      ],
    },
    {
      type: 'paragraph',
      content:
        'The global workspace has limited capacity—only some distinctions can be integrated at once. This explains the "bottleneck" of consciousness: we can process many things unconsciously but consciously experience only a small, integrated subset.',
      emphasis: 'key',
    },
    {
      type: 'heading',
      level: 2,
      content: 'When Integration Fails',
      id: 'when-integration-fails',
    },
    {
      type: 'paragraph',
      content:
        'Disorders and alterations of consciousness can be understood as disruptions to integration:',
    },
    {
      type: 'list',
      style: 'numbered',
      items: [
        {
          content:
            '**Split-brain patients**: Severing the corpus callosum disrupts integration between hemispheres, creating partial independence of conscious fields.',
        },
        {
          content:
            '**Dissociative disorders**: Psychological trauma can fragment the self/not-self boundary into multiple, partially independent self-models.',
        },
        {
          content:
            '**Meditation and psychedelics**: Practices or substances that reduce the sharpness of the self/not-self boundary alter the usual integration pattern, creating experiences of "ego dissolution" or "non-dual awareness."',
        },
        {
          content:
            '**Anesthesia**: General anesthetics disrupt the thalamocortical loops essential for integration, abolishing consciousness while leaving local processing intact.',
        },
        {
          content:
            '**Coma and vegetative states**: Severe brain injury can damage integration mechanisms, leaving unclear whether any unified conscious field persists.',
        },
      ],
    },
    {
      type: 'paragraph',
      content:
        'These phenomena support the framework: consciousness correlates with integration of distinction-states into a unified field, and disrupting integration disrupts consciousness.',
      emphasis: 'conclusion',
    },
  ],
  keyPoints: [
    '[IMPORTED from neuroscience] Conscious experience is unified despite distributed processing',
    '[INTERPRETED] Unity as thermodynamic optimization—integration more efficient than fragmentation',
    '[IMPORTED from neuroscience] The global workspace architecture (Baars) for conscious integration',
    '[INTERPRETED] The workspace bottleneck in terms of distinction-maintenance resources',
    '[IMPORTED from neuroscience] Integration failures (split-brain, anesthesia) disrupt consciousness',
  ],
};
